<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Symfony\Component\HttpFoundation\Response;

abstract class BaseController extends Controller
{
    public static function getSuccessModal(string $message)
    {
        return view('components.successModal', [
            'message' => $message,
        ]);
    }

    public static function getErrorModal(string $message)
    {
        return view('components.errorModal', [
            'message' => $message,
        ]);
    }

    // Authentifie l'utilisateur ou redirige si non connecte
    public function auth(Request $request): array
    {
        // Connexion de l'utilisateur
        if (Auth::check()) {
            if (Auth::user() !== null) {
                // Si l'utilisateur est déjà connecté, rediriger l'utilisateur vers la page qu'il souhaitait accéder à l'origine
                return ['success' => true];
            } else {
                dd("Erreur temporaire de test dans l'AuthController, c'est vraiment pas normal, l'authentification ne devrait pas être considérée comme valide alors que l'utilisateur n'existe pas !");
            }
        }

        // @var User $user
        $user = null;

        if (! app()->isLocal()) {
            // In production, try CAS authentication first
            if (isset($_SERVER['REMOTE_USER'])) {
                $login = $_SERVER['REMOTE_USER'];
                $user = User::where('login', $login)->first();
            } else {
                // CAS not configured, redirect to login page
                return ['success' => false, 'response' => redirect()->route('login')];
            }
        } else {
            // En local, on choisit un utilisateur de test
            $user =
                User::all()->first(
                    function (User $user) {
                        $roles = $user->getRoles();

                        // Rôle que l'utilisateur de test doit avoir (mettre null pour pas de rôle en particulier)
                        // Choix du rôle de l'utilisateur : Service financier, Directeur IUT, Département Info, Département SD, Département RT, Administrateur BD
                        $roleToHave = 'Département Info';

                        // Nombre de rôles que l'utilisateur de test doit avoir
                        $roleNumber = 1;

                        return (is_null($roleToHave) || $roles->first((fn (Role $role) => $role->getName() == $roleToHave))) && $roles->count() == $roleNumber;

                    }
                );
        }

        if (is_null($user)) {
            // Redirect to login page if user not found
            return ['success' => false, 'response' => redirect()->route('login')];
        }

        // Charger les permissions de l'utilisateur
        // TODO en changeant de page, les variables du modèle se déchargent.
        //  Malgré le stockage de l'utilisateur avec l'authentification (et peut-être même malgré la session)
        //  Pour optimiser plus de sorte à ce que le chargement de permissions ne se fait pas à chaque chargement de page
        //  il faudrait faire un cache pour stocker les utilisateurs qui se sont connectés
        $user->getPermissions(true);

        Auth::login($user);

        return ['success' => true];
    }

    // Intercepte chaque action pour forcer l'authentification
    public function callAction($method, $parameters)
    {
        // Charger l'utilisateur connecté pour être recupérable avec `Auth::user()`
        // S'il y a une erreur dans le processus d'authentification, retourner pour afficher la vue d'erreur

        $result = $this->auth(request());
        if (! $result['success']) {
            return $result['response'];
        }

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}
